### ISSUE TITLE
Multiplayer error

### ISSUE THREAD

**Issue by piratefinn** [Windows10CE/HereticSelection#1]
This may simply be a limitation unable to be fixed, but when connecting to a vanilla host in multiplayer (using UnmoddedVersion mod) you will spawn in without any of your loadout upon starting. They just show as the crossed out raven icons with 1 second cooldowns that do nothing. Can otherwise run around fine, just can't use any of the skills due to it not giving the items.

**Comment by Windows10CE** [comment]
This isn't possible to fix, due to the architecture of how characters and skills are communicated to the host. In general, you shouldn't expect help with issues caused by UnmoddedVersion.
